Bn 6 creazione dellendpoint
Flecart/battaglia-navale pull request #3
Opened 2022-08-13 16:22 UTC by 11THUNDER11

2022-08-13 19:35 UTC, Flecart requested changes
Le cose che vorrei che cambiassi sono soprattutto l'uso della classe invece dell'uso funzionale, l'uso degli hook, e selector by Id, che non ci sono in react. 

Per il resto sembra molto buono, anche se non lo ho guardato benissimo la parte backend dell'endpoint.

2022-08-13 19:35 UTC, Flecart commented on components/findMatch.tsx
> +export class FindMatch extends Component {
l'uso delle classi di React è molto vecchio, non dovresti seguire il tutorial ufficiale, ma i nuovi, che utilizzano gli hooks.
https://beta.reactjs.org/ (questo è il nuovo doc ufficiale che stanno facendo, ma è incompleto, comunque ha tutti i nuovi paradigmi).

2022-08-13 19:35 UTC, Flecart commented on components/findMatch.tsx
> +    changeStatus = () => {
tutte le funzioni per motivi di efficienza dovrebbero essere dei [`useCallback`](https://it.reactjs.org/docs/hooks-reference.html)

2022-08-13 19:35 UTC, Flecart commented on components/findMatch.tsx
> +    id : string = "";
gli stati interni dovrebbero essere dei `useState`

2022-08-13 19:35 UTC, Flecart commented on components/findMatch.tsx
> +                fetch(url, reqCreateGameOptions).then(response => response.json())
i side effect (ossia questi fetch che vanno fare richieste), dovrebbero essere messi nei [saga](https://medium.com/nerd-for-tech/saga-pattern-971d59be3722), ed essere triggerati da delle azioni. 

praticamente hai delle azioni, e vai a triggerare le azioni che vanno a chiamare i saga che ti chiamano i fetch. Il risultato è messo nello store, che utilizzi per aggiornare quello che hai sullo schermo. 

Questo è il pattern che ho visto usare, non so se è la migliore esistente, ma fatto sta che rende molto chiaro la struttura, e separano la logica di business con quella di presentazione, sulla pagina noi vorremmo solamente la logica di presentazione. 

Anche se però lo devo ancora finire di fare...

2022-08-13 19:35 UTC, Flecart commented on components/findMatch.tsx
> +
cosa sono questi spazi a casissimo :laughing:

2022-08-13 19:35 UTC, Flecart commented on components/findMatch.tsx
> +        }
Con React non dovresti andare a modificare il contenuto mostrato andando a modificare l'HTML. 
Meglio il [conditional rendering](https://it.reactjs.org/docs/conditional-rendering.html)

2022-08-13 19:35 UTC, Flecart commented on components/findMatch.tsx
> +                        name : document.getElementById("playerName").value ,
con react non dovresti mai andare a cercare l'Id. Cioè alla fine ti funziona, ma non è un pattern solito a react

2022-08-13 19:35 UTC, Flecart commented on components/findMatch.tsx
> +                this.id = data.id;
non sono sicuro che funzioni, il `this` di javascript è [molto strano](https://blog.bitsrc.io/what-is-this-in-javascript-3b03480514a7), sei sicuro di averlo provato e ricevi i valori giusti?.
Comunque con il react funzionale poi non ti dovrai fare questi problemi

2022-08-13 19:35 UTC, Flecart commented on components/findMatch.tsx
> +            document.getElementById("playerName").disabled = false;
uguale a sopra, dovresti utilizzare il rendering condizionale per disabilitarlo

2022-08-13 19:35 UTC, Flecart commented on components/findMatch.tsx
> +        const name = document.getElementById("playerName").value;
uguale a sopra riguardo sto pattern per prendere l'ID

2022-08-13 19:35 UTC, Flecart commented on components/findMatch.tsx
> +            document.getElementById("playerName").disabled = true;
uguale a sopra, rendering condizionale

2022-08-13 19:35 UTC, Flecart commented on components/findMatch.tsx
> +
spazi pluff pluff :fire:

2022-08-13 19:35 UTC, Flecart commented on components/findMatch.tsx
> +import React, {Component} from "react";
il nome del componente mi sta dicendo più cosa deve fare in modo molto specifico. I componenti di solito sono cose visuali che fanno qualcosa di generalizzabile, ad esempio `searchBar`, `button`, che poi li puoi customizzare con le funzioni che più ti aggradano

2022-08-13 19:35 UTC, Flecart commented on pages/api/test/mockTest.ts
>  }
per fare i test delle richieste puoi usare postman, o farle da curl. Ma è uguale fai come ti è più comodo, qui presento solo delle alternative.

2022-08-13 19:35 UTC, Flecart commented on model/battleship/Structs.ts
> +            return new Error(`Position is not well formed: `);
non ho capito il senso di questo cambio

2022-08-13 19:35 UTC, Flecart commented on model/battleship/Structs.ts
> +            return new Error(`Segment is not well formed: `);
nemmeno di questo

2022-08-13 19:35 UTC, Flecart commented on pages/api/game/findGame/index.tsx
> +    //TODO: create the endpoint for the request
manca la validazione del body della richiesta. 
Con un endpoint esposto non possiamo assumere niente, l'utente può potenzialmente inviare di tutto.

2022-08-13 19:35 UTC, Flecart commented on pages/index.tsx
>      </div>
invece di divs che vengono realmente mostrati come divs, puoi usare i react fragments, ma dato che è un compente solo puoi anche non wrapparlo proprio.

2022-08-13 19:35 UTC, Flecart commented on components/findMatch.tsx
> +            <div>
usa react fragments invece che div

2022-08-13 19:35 UTC, Flecart commented on components/findMatch.tsx
> +            <div>
praticamente sintassi è così 

```ts
<>
    <TextField id="playerName" label="Player name" variant="outlined" required/>

    <ToggleButtonGroup>
        <ToggleButton value="search" id = "search" onClick={this.send}>
            Find match
        </ToggleButton>
    </ToggleButtonGroup>
</>
```
sono dei wrapper fantasma, nell ápp di fuori non vedi che c'è un wrapper (come invece sarebbe stato, ci sarebbe un altro div nel DOM), serve solo a react a capire che stanno insieme

2022-08-14 09:41 UTC, 11THUNDER11 commented on components/findMatch.tsx
> +                        name : document.getElementById("playerName").value ,
Quali sarebbero i pattern giusti, cioè non ne conosco nessuno ecco.

2022-08-14 09:42 UTC, 11THUNDER11 commented on components/findMatch.tsx
> +
Per aggiungere linee di codice XD

2022-08-14 09:43 UTC, 11THUNDER11 commented on model/battleship/Structs.ts
> +            return new Error(`Position is not well formed: `);
L'ho commentato per poter fare il run dell'applicazione, mi segnalava un'errore.

2022-08-14 09:43 UTC, 11THUNDER11 commented on model/battleship/Structs.ts
> +            return new Error(`Segment is not well formed: `);
Come ho detto sopra

2022-08-14 10:47 UTC, Flecart commented on components/findMatch.tsx
> +
eeee xD, comunque ora se fai un rebase sul main hai il formatter, se runni `npm run format` oppure `yarn format` ti formatta tutto il codice.

2022-08-14 10:48 UTC, Flecart commented on model/battleship/Structs.ts
> +            return new Error(`Position is not well formed: `);
Ah, proprio ti crashava??? Che strano. L'errore è di lint, non del programma, ti dovrebbe runnare lo stesso.

2022-08-14 10:49 UTC, Flecart commented on components/findMatch.tsx
> +                        name : document.getElementById("playerName").value ,
https://blog.logrocket.com/react-component-design-patterns-2022/

2022-08-17 08:21 UTC, closed without merging